[context."develop"]
    command = "gatsby build"
    publish = "public/"

[context."feature/gatsbyjs"]
    command = "gatsby build"
    publish = "public/"

[context."feature/nextjs"]
    command = "npm run build"
    publish = "out/"
